version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db-test:
    container_name: postgres_test
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: flask run
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
      - db-test

volumes:
  postgres_data:
